apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-dev-service-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app-dev
  endpoints:
    - port: app-port
      path: /staging/v1/metrics-text
  namespaceSelector:
    matchNames:
      - app-dev
