apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
  labels:
    app: gh-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: workdir
        hostPath:
          path: /tmp/github-runner-terraform
      containers:
        - name: app-dev
          image: myoung34/github-runner:2.301.0-ubuntu-bionic
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
          - name: RUNNER_TOKEN
            valueFrom:
              secretKeyRef:
                name: runner-token
                key: RUNNER_TOKEN
                optional: false
          - name: RUNNER_SCOPE
            value: "org"
          - name: ORG_NAME
            value: polinetworkorg
          - name: REPO_URL
            value: https://github.com/polinetworkorg/terraform
          - name: RUNNER_NAME_PREFIX
            value: gh-action
          - name: RUNNER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RUNNER_WORKDIR
            value: /tmp/github-runner-terraform
          volumeMounts:
          - name: dockersock
            mountPath: /var/run/docker.sock
          - name: workdir
            mountPath: /tmp/github-runner-terraform
