apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
  labels:
    app: gh-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      containers:
        - name: app-dev
          image: myoung34/github-runner:2.301.0-ubuntu-bionic
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
          - name: RUNNER_TOKEN
            valueFrom:
              secretKeyRef:
                name: runner_token
                key: RUNNER_TOKEN
                optional: false
