apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner
  labels:
    app: gh-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gh-runner
  template:
    metadata:
      labels:
        app: gh-runner
    spec:
      terminationGracePeriodSeconds: 400
      containers:
        - name: app-dev
          image: myoung34/github-runner:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", 'curl -sL https://aka.ms/InstallAzureCLIDeb | bash']
          env:
          - name: ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: runner-token
                key: RUNNER_TOKEN
                optional: false
          - name: EPHEMERAL
            value: "1"
          - name: RUN_AS_ROOT
            value: "false"
          - name: REPO_URL
            value: https://github.com/polinetworkorg/terraform
          - name: RUNNER_NAME_PREFIX
            value: gh-action
          - name: RUNNER_WORKDIR
            value: "/home/runner/"
          - name: RUNNER_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
