apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-rooms
  template:
    metadata:
      labels:
        app: bot-rooms
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_dev:2c450bb1157a53d5f620c0d541198cdd2e743214
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
