apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-rooms
  template:
    metadata:
      labels:
        app: bot-rooms
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_dev:8dd659f2d2e5d855337882c69e8f53a69610a352
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "300m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
