working_dir: core
compose_files: [compose.yaml]
prune_images: false
webhook_filter: ^refs/heads/vm$
auto_discovery:
  enabled: true
  depth: 1
  delete: true
  remove_volumes: false
  remove_images: false
---
working_dir: apps
compose_files: [compose.yaml]
prune_images: false
webhook_filter: ^refs/heads/vm$
auto_discovery:
  enabled: true
  depth: 1
  delete: true
  remove_volumes: false
  remove_images: false
