apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-prod
  template:
    metadata:
      labels:
        app: bot-prod
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_prod:eefccdae7d8d2f74deae6ab872cac38b01a1e401
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: git
            mountPath: /git
          - name: ssh
            mountPath: /home/botexecuter/.ssh
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: git
          secret:
            secretName: git-config
        - name: ssh
          secret:
            secretName: ssh-config
      

