apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-prod
  template:
    metadata:
      labels:
        app: bot-prod
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_prod:3adfb0ead439d4cfdbb889a1ebf3050d489bcedb
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: git
            mountPath: /git
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "mkdir ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && eval `ssh-agent -s`"]
          resources:
            requests:
              cpu: "150m"
              memory: "200Mi"
            limits:
              cpu: "250m"
              memory: "400Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: git
          secret:
            secretName: git-config
