apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: monitoring-telegram-bot-token
      remoteRef:
        key: monitoring-telegram-bot-token
