apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-prod
  template:
    metadata:
      labels:
        app: app-prod
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: app-prod
          image: not_initialized
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "300m"
              memory: "500Mi"
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
      volumes:
        - name: config
          secret:
            secretName: app-config-secret
      

