apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bot-mat-spc
  namespace: bot-mat
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "31ef9b42-b1c6-4bbc-bbce-3cf2faa1c8cb"
    tenantId: "7f8cafc8-4314-4070-9744-fe02f91bcb21"
    keyvaultName: "kv-polinetwork"
    objects: |
      array:
        - |
          objectName: prod-bot-mat-token            
          objectType: secret
  secretObjects:
    - secretName: azure-kv
      type: Opaque
      data:
        - objectName: prod-bot-mat-token            
          key: bot-token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-mat-maintenance
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bot-mat-maintenance
  template:
    metadata:
      labels:
        app: bot-mat-maintenance
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
      containers:
        - name: bot-mat-maintenance
          image: ghcr.io/polinetworkorg/bot-maintenance@sha256:934dd96e237568911ebb7ff8bb109f36344e80e8c1270ffb42e170fb7d3d9024 
          imagePullPolicy: IfNotPresent
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-kv
                  key: bot-token
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "bot-mat-spc"
