apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-kv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: azure-kv
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: auth-secret
      remoteRef:
        key: auth-better-auth-secret
    - secretKey: entra-client-id
      remoteRef:
        key: auth-entra-client-id
    - secretKey: entra-client-secret
      remoteRef:
        key: auth-entra-client-secret
    - secretKey: google-client-id
      remoteRef:
        key: auth-google-client-id
    - secretKey: google-client-secret
      remoteRef:
        key: auth-google-client-secret
    - secretKey: telegram-client-id
      remoteRef:
        key: auth-telegram-client-id
    - secretKey: telegram-client-secret
      remoteRef:
        key: auth-telegram-client-secret
    - secretKey: db-pass
      remoteRef:
        key: postgres-root-password
    - secretKey: db-user
      remoteRef:
        key: postgres-root-user
