apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:53bcf1d5e3ba7fadc1d1a773aec9d454f0ea00f3
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          securityContext:
            runAsUser: 7999
            fsGroup: 7999
            fsGroupChangePolicy: "OnRootMismatch"
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

