apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:641a2989fb4b4a7f84f703588ec7038074dbff50
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          securityContext:
            runAsUser: 7999
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

