apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:a191ebe4335d8531509755d96c365a93495b8f0e
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: tz-rome
            mountPath: /etc/localtime
      volumes:
      - name: config
        secret:
          secretName: bot-config-secret
      - name: tz-rome
        hostPath:
          path: /usr/share/zoneinfo/Europe/Rome
