apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:60bea73f0c977a13837d79da08fbb2afc586c44b
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "50m"
              memory: "50Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

