apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:6f5d76abbb12c0793faead40d713163fc84465cb
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            limits:
              cpu: "0.5"
              memory: "1000Mi"
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

