apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:dd70e0dbb2d95621350fd4d4ceacc2bda0c13494
          # command: [ "sleep", "10000" ]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Rome
            type: File
      

