apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:5927f618a15d6ebd640f2c9ccabb92145100e91a
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

