apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:e12dc37cc0f090623f705e473ae26e2690201e0c
          command: ["sleep", "1000"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: tz-config
            mountPath: /etc/localtime
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Europe/Rome
            type: File
      

