apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:63ecd3e64be03d98995e3561f0e84da4cf2d810e
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          securityContext:
            runAsUser: 7999
            runAsGroup: 7999
            allowPrivilegeEscalation: false
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

