apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
        image: polinetwork/botcsharp_dev:a0b811fadcb23eb3ba8f76188511eb950a7bf4f6
          # command: ['sh', '-c', 'cp /config_readonly/* /config/']
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
            readOnly: false
      volumes:
      - name: config
        secret:
          secretName: bot-config-secret
