apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:d645ca702d75c8059e2e05a6700997c46a83d84b
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

