apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:54d6c08a1363dcacc393ba5be4878a4ffd9b5fbc
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: "/config"
            subPath: bots_info.json
      volumes:
      - name: config
        secret:
          secretName: bot-config-secret