apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:71ff947f86940a76bc4ea3607711a408fd0f010b
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: "/config1"
            subPath: bots_info.json
      volumes:
      - name: config
        secret:
          secretName: bot-config-secret