apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:e80a00c79f4088c25d1547b2e550bf3f0c9b54a8
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

