apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-kv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: azure-kv
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: azure-client-id
      remoteRef:
        key: backend-azure-client-id
    - secretKey: azure-client-secret
      remoteRef:
        key: backend-azure-client-secret
    - secretKey: azure-tenant-id
      remoteRef:
        key: backend-azure-tenant-id
    - secretKey: encryption-key
      remoteRef:
        key: backend-encryption-key
    - secretKey: auth-github-id
      remoteRef:
        key: backend-auth-github-secret
    - secretKey: auth-github-secret
      remoteRef:
        key: backend-auth-github-id
    - secretKey: auth-secret
      remoteRef:
        key: backend-auth-secret
    - secretKey: db-pass
      remoteRef:
        key: postgres-root-password
    - secretKey: db-user
      remoteRef:
        key: postgres-root-user
