apiVersion: apps/v1
kind: Deployment
metadata:
  name: aule-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aule-bot
  template:
    metadata:
      labels:
        app: aule-bot
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: aule-bot
          image: polinetwork/aule_bot_prod:0e1aed4bbc0a57689f26bad4a88edc6b8bc7da4d
          imagePullPolicy: IfNotPresent
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: aule-bot-secret
                  key: TOKEN
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "400m"
              memory: "400Mi"
