apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-kv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: azure-kv
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: db-pass
      remoteRef:
        key: postgres-polinetcc-password
    - secretKey: db-user
      remoteRef:
        key: postgres-polinetcc-user
    - secretKey: oidc-client-id
      remoteRef:
        key: polinetcc-oidc-client-id
    - secretKey: session-secret
      remoteRef:
        key: polinetcc-session-secret
