apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-mat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-mat
  template: 
    metadata:
      labels:
        app: bot-mat
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-mat
          image: polinetwork/botcsharp_prod:d68f38484c9a3a2ecec83f8b7979443b5e5b7798
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: mat-persistent-storage
            mountPath: /Repos
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "150m"
              memory: "400Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: mat-persistent-storage
          persistentVolumeClaim:
            claimName: bot-pvc
      

