apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-mat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-mat
  template:
    metadata:
      labels:
        app: bot-mat
    spec:
      containers:
        - name: bot-mat
          image: polinetwork/botcsharp_dev:c2757e1d916edf5e66f6d3cc0d0880dcdf265852
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: mat-persistent-storage
            mountPath: /Repos
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: mat-persistent-storage
          persistentVolumeClaim:
            claimName: bot-pvc
      

