apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-mat
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bot-mat
  template: 
    metadata:
      labels:
        app: bot-mat
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-mat
          image: polinetwork/botcsharp_prod:7844a9f576903261020208382d8d96755fd144e7
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          - name: mat-persistent-storage
            mountPath: /Repos
          resources:
            requests:
              cpu: "50m"
              memory: "300Mi"
            limits:
              cpu: "150m"
              memory: "500Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: mat-persistent-storage
          persistentVolumeClaim:
            claimName: bot-pvc
      

