apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-dev
  template:
    metadata:
      labels:
        app: bot-dev
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: bot-dev
          image: polinetwork/botcsharp_dev:2eac553f9df438d66399ec941667de3c1d054d64
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "400Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

