apiVersion: apps/v1
kind: Deployment
metadata:
  name: newbot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newbot-prod
  template:
    metadata:
      labels:
        app: newbot-prod
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: newbot-prod
          image: "polinetwork/polinetworkbot:ModerationBot-main-4cbe012e6e6de8cb6d8d97f10c57504a74483a72"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
            - name: git
              mountPath: /git
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "mkdir ~/.ssh/ && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts && eval `ssh-agent -s`"]
          resources:
            requests:
              cpu: "150m"
              memory: "200Mi"
            limits:
              cpu: "250m"
              memory: "400Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
        - name: git
          secret:
            secretName: git-config
