---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc
  labels:
    app: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc
  template:
    metadata:
      labels:
        app: mc
    spec:
      containers:
        - name: mc
          image: polinetwork/amp_instance_mgr_kubernetes:e42e8c9f5cf7efdceedde62dc5b94fb43713a5ca
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: home
              mountPath: /home/amp/.ampdata
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mc-secret
                  key: PASSWORD
            - name: LICENCE
              valueFrom:
                secretKeyRef:
                  name: mc-secret
                  key: AMP_LICENSE
            - name: UID
              value: "7999"
            - name: GID
              value: "7999"
          resources:
            requests:
              cpu: 800m
              memory: 1000Mi
            limits:
              cpu: 1800m
              memory: 3000Mi
          ports:
            - containerPort: 8080
            - containerPort: 3306
      volumes:
        - name: home
          persistentVolumeClaim:
            claimName: mc-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: ui
    - port: 3306
      targetPort: 3306
      name: mc
  selector:
    app: mc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mc-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
    - hosts:
        - mc.polinetwork.org
      secretName: mc-tls
  rules:
    - host: mc.polinetwork.org
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: mc-service
                port:
                  name: ui
    - host: mc.polinetwork.org
      http:
        paths:
          - path: /mc/(.*)
            pathType: Prefix
            backend:
              service:
                name: mc-service
                port:
                  name: mc
