apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: polinetwork/polifemo_backend_dev:81727ad1281d1ceb4dd24423640e4795b7f4956b
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999

