apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: polinetwork/polifemo_backend_dev:cb1d217999b9b1f5b4b7d2e33e09b7b17e55f110
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      volumes:
        - name: config
          secret:
            secretName: app-secrets
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999

