apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: not_initialized
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
      volumes:
        - name: config
          secret:
            secretName: app-config-secret
      

