apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dev
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-dev
  template:
    metadata:
      labels:
        app: app-dev
    spec:
      containers:
        - name: app-dev
          image: polinetwork/polifemo_backend_dev:deda8070d73d07577d70995025e333040166c939
          # image: polinetwork/simple_test_image:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
          ports:
            - containerPort: 5000
          env:
            - name: TITLE
              value: "Welcome to Azure Kubernetes Service (AKS)"
      volumes:
        - name: config
          secret:
            secretName: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: app-dev-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 5000
  selector:
    app: app-dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-dev-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-dev-service
                port:
                  number: 8000
