apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-prod
  template:
    metadata:
      labels:
        app: bot-prod
    spec:
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_prod:78f3e8f1c04b0c2e2d07d2bc568b5b8eabbf535e
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

