apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-prod
  template:
    metadata:
      labels:
        app: bot-prod
    spec:
      containers:
      - name: bot-prod
          image: polinetwork/botcsharp_prod:754271f739f1aef8069d2cabc5231159cfde98cc
        imagePullPolicy: IfNotPresent
