apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-prod
  template:
    metadata:
      labels:
        app: bot-prod
    spec:
      containers:
        - name: bot-prod
          image: polinetwork/botcsharp_prod:57251a963b9bc23e91c8a4e20eeac9be609a826b
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config
            mountPath: /config
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "500m"
              memory: "1000Mi"
      volumes:
        - name: config
          secret:
            secretName: bot-config-secret
      

