apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-kv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: azure-kv
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: db-user
      remoteRef:
        key: postgres-root-user
    - secretKey: db-pass
      remoteRef:
        key: postgres-root-password
