apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: bot-rooms-spc
  namespace: bot-rooms
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "31ef9b42-b1c6-4bbc-bbce-3cf2faa1c8cb"
    tenantId: "7f8cafc8-4314-4070-9744-fe02f91bcb21"
    keyvaultName: "kv-polinetwork"
    objects: |
      array:
        - |
          objectName: dev-aule-bot-token            
          objectType: secret
        - |
          objectName: dev-db-user
          objectType: secret
        - |
          objectName: dev-db-password
          objectType: secret
  secretObjects:
    - secretName: azure-kv
      type: Opaque
      data:
        - objectName: dev-aule-bot-token
          key: bot-token
        - objectName: dev-db-user
          key: db-user
        - objectName: dev-db-password
          key: db-pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-rooms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-rooms
  template:
    metadata:
      labels:
        app: bot-rooms
    spec:
      securityContext:
        runAsUser: 7999
        runAsGroup: 7999
        fsGroup: 7999
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: botcsharp-config
          image: ghcr.io/polinetworkorg/botcsharp-config@sha256:709e08ac99ac674ac43181f29a1d3f1e16c315d47b3577b9af3133bca957e79f
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: false
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          env:
            - name: OUT_DIR
              value: "/config"
            - name: CREATE_DB_CONFIG
              value: "true"

            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azure-kv
                  key: bot-token
            - name: BOT_ON_MESSAGES
              value: "au"

            - name: DB_DATABASE
              value: "polinetwork_test"
            - name: DB_HOST
              value: "mariadb-service.mariadb.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: azure-kv
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-kv
                  key: db-pass

      containers:
        - name: bot-prod
          image: ghcr.io/polinetworkorg/botcsharp_dev@sha256:da4fe60a3189f93ca85cafbceddfa4e0c7e1b9873ef62c6bf023cce524f1a4be
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              cpu: "10m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
      volumes:
        - name: config
          emptyDir: {}
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "bot-rooms-spc"
