apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.9.4
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: MARIADB_ROOT_PASSWORD
              optional: false
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "./scripts/startup.sh"]
        resources:
            requests:
              cpu: "50m"
              memory: "500Mi"
            limits:
              cpu: "100m"
              memory: "1000Mi"
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        - name: mariadb-initdb
          mountPath: /docker-entrypoint-initdb.d
        - name: mariadb-scripts
          mountPath: /scripts
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-storage-claim
      - name: mariadb-initdb
        secret:
          secretName: initdb
      - name: mariadb-scripts
        configMap:
          name: scripts
          defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mariadb-ingress
  annotations:
    kubernetes.io/ingress.class: "addon-http-application-routing"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - api.polinetwork.org
      secretName: mariadb-tls
  rules:
    - host: api.polinetwork.org
      http:
        paths:
          - path: /db(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mariadb-service
                port:
                  name: mariadb
