apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure-security.yaml
  - infrastructure-storage.yaml
  - infrastructure-traefik.yaml
  - infrastructure-external-secrets.yaml
  - infrastructure-secret-stores.yaml
  - infrastructure-cloudflared.yaml
  - infrastructure-image-automation.yaml
  - infrastructure-node-exporter.yaml
  - infrastructure-flux-web.yaml
  - infrastructure-fluxcd-ui.yaml
  - apps
