apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azure-kv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: kv-pn-apps
  target:
    name: azure-kv
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: bot-token
      remoteRef:
        key: bot-ts-token
    - secretKey: influxdb-token
      remoteRef:
        key: influxdb-token
    - secretKey: openai-api-key
      remoteRef:
        key: openai-api-key
    - secretKey: oauth-private-jwk
      remoteRef:
        key: bot-ts-private-jwk
